### PR TITLE
Fix typo in renga-python pointer

### LINKED ISSUE #104: README.rst: typo in renga-python URL
Clicking on the _renga-python_ link in the README gives an error because it points to github/com rather than github.com.

### PR DESCRIPTION
**Pull request by sleinen**
Fixes #104

### CODE REVIEW

**Comment by jirikuncar** [comment]
Hi @sleinen,
Thank you very much for your contribution. We would like to ask you to sign the contributor license agreement so we can include your changes in the @SwissDataScienceCenter organisation.

[SDSC_Contributor_License_Agreement_v1.0.pdf](https://github.com/SwissDataScienceCenter/renga/files/1358530/SDSC_Contributor_License_Agreement_v1.0.pdf)

If you have any questions, please do not hesitate to [contact us](mailto:contact@datascience.ch).

Best,
Jiri

**Comment by sleinen** [comment]
Thanks @jirikuncar. We're trying to get the CLA in place for all people at SWITCH who are likely to contribute.  Stay tuned...

**Comment by sleinen** [comment]
Took a while, but my boss sent the signed CLA earlier today, including my name (among others).

**Comment by sleinen** [comment]
@jirikuncar Can you check the status of this patch and my (colleagues') general eligibility for contributing to Renga? I know there have been goings-on in the background between our respective managements, but I have no idea what the resulting situation is.  Would be happy to do anything I can if/as necessary to unblock this.  Please advise!

**Comment by rokroskar** [comment]
closing this for now as per the discussions that took place in January. Thanks @sleinen for spotting the typo!

**Pull request closed without merging**
